version: "3.9"
services:

  mariadb:
    restart: always
    image: mariadb
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_vol:/var/lib/mysql

  wordpress:
    build: requirements/wordpress/
    restart: always
    env_file: .env
    ports:
      - "9000:9000" 
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    depends_on:
      - mariadb

  nginx:
    build: requirements/nginx/
    restart: always
    env_file: .env
    ports:
      - "443:443"
#nginx will need to use the wordpress volume to serve static files
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    depends_on:
      - wordpress


#"local" :The volume is on the host machine.
#"device":Where should the volume be stored on the host machine.
#"o:bind":Bind the volume to a directory in the container.

volumes:

  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/wordpress_volume

  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mariadb_volume

networks:
  network42:
    driver: bridge
