version: "3.9"
services:

#  wordpress:
#    build: requirements/wordpress/
#    environement:
#      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
#      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
#      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
#      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
#    restart: always
#    ports:
#      -  "9000:9000" 

  nginx:
    build: 
      context: requirements/nginx/
      args:
        - CERTS_=${CERTS_}
        - DOMAIN_NAME=${DOMAIN_NAME}
    environment:
      - CERTS_=${CERTS_}
      - DOMAIN_NAME=${DOMAIN_NAME}
    restart: always
    ports:
      -  "443:443"
#    depends_on:
#      wordpress
