version: "3.9"
services:

  mariadb:
    image: mariadb
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - md:/var/lib/mysql


  wordpress:
    build: requirements/wordpress/
    environement:
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
    restart: always
    ports:
      -  "9000:9000" 

  nginx:
    build: requirements/nginx/
    environment:
      - CERTS_=${CERTS_}
      - DOMAIN_NAME=${DOMAIN_NAME}
    restart: always
    ports:
      -  "443:443"
    depends_on:
      wordpress


#local= The volume is on the host machine.
#devie= Where should the volume be stored on the host machine.
volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/wordpress

networks:
  network42:
    driver: bridge
